name: diversid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.0.0
  go_router: ^13.2.5
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.1
  hive_flutter: ^1.1.0
  freezed: ^2.1.1
  equatable: ^2.0.5
  overlay_support: ^2.1.0
  intl: ^0.19.0
  flutter_otp_text_field: ^1.1.3+2
  modal_bottom_sheet: ^3.0.0
  auto_size_text: ^3.0.0
  signature: ^5.5.0
  flutter_tts: ^4.0.2
  text_to_speech: ^0.2.3
  speech_to_text: ^6.6.2
  record: ^5.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.5.0+1
  flutter_native_splash: ^2.4.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#20B9BA"
  android_12:
    color: "#20B9BA"


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svgs/